gui:
  theme:
    backgroundColor:
      - "#1e1e2e"
    textColor:
      - "#cdd6f4"
    selectedLineBgColor:
      - "#3a3a3a"
    selectedLineFgColor:
      - "#ffffff"
    activeBorderColor:
      - "#cdd6f4"
    inactiveBorderColor:
      - "#6c7086"
    optionsTextColor:
      - "#a6adc8"
  nerdFontsVersion: "3"
  showFileIcons: true
  border: rounded
  spinner:
    # The frames of the spinner animation.
    frames:
      - 'O'
      - 'U'
      - 'u'
      - 'o'
      - 'u'
      - 'U'

    # The "speed" of the spinner in milliseconds.
    rate: 100
