unbind r
bind r source-file ~/.tmux.conf

# Set prefix
set -g prefix C-f

# Enable mouse
set -g mouse on

# Make every new window follow the pwd of the last
bind c new-window -c "#{pane_current_path}"
set -g automatic-rename off

# Make window's index start at 1
set -g base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Set vim movement keys
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set the status position to the top
set-option -g status-position top

# Plugins

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Lackluster theme
source-file ~/.tmux/themes/lackluster.tmux

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
